FROM --platform=linux/arm64 localhost:5001/clawmanager-openclaw/openclaw@sha256:64d12df787a9d46a883c23b9870b1763f1a0099e5fee1106d86901b7c666ff45

COPY --chmod=0644 control-ui/index.html /usr/local/lib/node_modules/openclaw/dist/control-ui/index.html
COPY --chmod=0644 control-ui/assets/index-M4TNVXB3.js /usr/local/lib/node_modules/openclaw/dist/control-ui/assets/index-M4TNVXB3.js
COPY --chmod=0644 control-ui/assets/i18n-B06L7jQN.js /usr/local/lib/node_modules/openclaw/dist/control-ui/assets/i18n-B06L7jQN.js
COPY --chmod=0644 control-ui/assets/zh-CN-B26mMdbY.js /usr/local/lib/node_modules/openclaw/dist/control-ui/assets/zh-CN-B26mMdbY.js
